defmodule Keyverse.Html do
  @moduledoc "Server-rendered HTML shells; client JS/CSS from priv/static."

  alias Keyverse.{Config, Note, Scope, Tree}

  def esc(nil), do: ""
  def esc(s), do: Plug.HTML.html_escape(to_string(s))

  def page(title, body, opts \\ []) do
    base = Keyword.get(opts, :base, "")
    man_scope = Keyword.get(opts, :manifest_scope, base)
    man_path = if man_scope == "", do: "/manifest.webmanifest", else: "#{man_scope}/manifest.webmanifest"
    pwa_head = static_text("pwa-head.html")
    fathom = fathom_tag()

    """
    <!doctype html><html lang="en"><head><meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <title>#{esc(title)}</title>
    #{pwa_head}
    <link rel="manifest" href="#{esc(man_path)}">
    <link rel="stylesheet" href="/app.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@phosphor-icons/web@2.1.2/src/regular/style.css" crossorigin="anonymous">
    <script>window.BASE=#{Jason.encode!(base)};var BASE=window.BASE;</script>
    <script src="/crypto.js"></script>
    <script>if(window.VP_CRYPTO)VP_CRYPTO.ingestHash();</script>
    #{fathom}
    </head><body>#{body}
    <script src="/pwa-boot.js"></script>
    </body></html>
    """
  end

  defp static_text(name) do
    path = Path.join(Config.static_dir(), name)

    case File.read(path) do
      {:ok, body} ->
        body
        # Extractor banners are /* … */ — invalid as HTML and paint as page text if inlined in <head>.
        |> String.replace(~r/\A\s*\/\*[\s\S]*?\*\/\s*/, "")
        |> String.replace(~r/\n\/\* generated by scripts\/extract_client_js\.mjs[\s\S]*?\*\/\n/, "\n")

      _ ->
        ""
    end
  end

  defp fathom_tag do
    site = Config.fathom_site()

    if site == "" do
      ""
    else
      ~s(<script src="https://cdn.usefathom.com/script.js" data-site="#{esc(site)}" defer></script>)
    end
  end

  def site_footer(install? \\ false) do
    install =
      if install? do
        ~s(<button type="button" class="pwa-install" id="pwa-install">Install app</button>)
      else
        ""
      end

    """
    <footer class="site-foot ui">#{install}<span class="muted">no account · just your key</span></footer>
    """
  end

  def render_setup(opts \\ []) do
    error = Keyword.get(opts, :error, "")
    suggested = Keyword.get(opts, :suggested) || "quiet-river-lantern-notes"

    err =
      if error != "",
        do: ~s(<p class="login-error" role="alert">#{esc(error)}</p>),
        else: ""

    body = """
    <div class="login">
      <h1>keyverse</h1>
      <p class="lead">Create your notes. Your key is four words — no account.</p>
      #{err}
      <form class="login-form" method="post" action="/setup" id="setup-form">
        <label for="door">Your key</label>
        <input type="text" id="door" name="door"
          value="#{esc(suggested)}"
          placeholder="four-words-like-this"
          autocomplete="off" autocapitalize="off" spellcheck="false"
          required autofocus>
        <button type="submit" class="login-btn" name="intent" value="claim">Create and open notes</button>
        <button type="submit" class="login-btn login-btn-secondary" name="intent" value="generate"
          formnovalidate>Suggest another key</button>
      </form>
      <p class="muted" style="margin-top:1rem"><a class="back-btn" href="/">← Already have a key?</a></p>
      <details class="login-more">
        <summary>How keys work</summary>
        <p>Your key is four words that open <strong>your</strong> pack of notes — also the link
          (e.g. <code>…/quiet-river-lantern-notes/</code>). Bookmark it. Anyone with the link can open the same notes.
          A different key is a different pack.</p>
      </details>
      #{site_footer(false)}
    </div>
    <script>
    (function () {
      var KEY = "vp_door_key";
      var form = document.getElementById("setup-form");
      var input = document.getElementById("door");
      if (!form || !input) return;
      form.addEventListener("submit", function (e) {
        var intent = (e.submitter && e.submitter.value) || "claim";
        if (intent === "generate") return;
        var v = (input.value || "").trim().toLowerCase().replace(/\\s+/g, "-");
        if (v) try { localStorage.setItem(KEY, v); } catch (err) {}
      });
    })();
    </script>
    """

    page("keyverse · setup", body, base: "", manifest_scope: "")
  end

  def render_enter(opts \\ []) do
    error = Keyword.get(opts, :error, "")
    local? = Keyword.get(opts, :local, false)

    err =
      if error != "",
        do: ~s(<p class="login-error" role="alert">#{esc(error)}</p>),
        else: ""

    create_link = """
    <p class="muted" style="margin-top:1.1rem">
      <a href="/setup">Create a new key</a>
    </p>
    <p class="muted" style="margin-top:.55rem">
      <a href="/local" data-testid="open-local-mount">Open notes on this device</a>
    </p>
    """

    key_form = fn required, autofocus, btn ->
      """
      <form class="login-form" method="get" action="/enter" id="login-form">
        <label for="door">Your key</label>
        <input type="text" id="door" name="door"
          placeholder="four-words-like-this"
          autocomplete="username" autocapitalize="off" spellcheck="false"
          #{if required, do: "required", else: ""} #{if autofocus, do: "autofocus", else: ""}>
        <button type="submit" class="login-btn">#{esc(btn)}</button>
      </form>
      """
    end

    body_inner =
      if local? do
        """
        <h1>keyverse</h1>
        <p class="lead">Your scripture notes.</p>
        #{err}
        <a class="login-btn" href="#" id="open-my-notes">Open my notes</a>
        <details class="login-more"#{if error != "", do: " open", else: ""}>
          <summary>Use a different key</summary>
          #{key_form.(true, error != "", "Continue")}
        </details>
        #{create_link}
        """
      else
        """
        <h1>keyverse</h1>
        <p class="lead">Open your notes with your key.</p>
        #{err}
        #{key_form.(true, true, "Open notes")}
        #{create_link}
        <div class="ios-install-hint" id="ios-install-hint">
          <strong>Install on this device:</strong> Share → <strong>Add to Home Screen</strong>.
        </div>
        <details class="login-more">
          <summary>Don’t have a key?</summary>
          <p><a href="/setup">Create a new key</a> — four words, no account. Bookmark the page after you open.</p>
          <p>Opening someone else’s notes? Ask them for their link.</p>
        </details>
        #{site_footer(true)}
        """
      end

    body = """
    <div class="login">#{body_inner}</div>
    <script>
    (function () {
      var KEY = "vp_door_key";
      var input = document.getElementById("door");
      var form = document.getElementById("login-form");
      var openMine = document.getElementById("open-my-notes");
      try {
        var saved = localStorage.getItem(KEY);
        if (saved) {
          if (input && !input.value) input.value = saved;
          if (openMine) openMine.href = "/" + saved.replace(/\\s+/g, "-").toLowerCase() + "/";
        } else if (openMine) {
          openMine.href = "/setup";
          openMine.textContent = "Create my notes";
        }
      } catch (e) {}
      if (input && form) {
        form.addEventListener("submit", function () {
          var v = (input.value || "").trim().toLowerCase().replace(/\\s+/g, "-");
          if (v) try { localStorage.setItem(KEY, v); } catch (e) {}
        });
      }
      var ua = navigator.userAgent || "";
      var isIOS = /iPad|iPhone|iPod/.test(ua) || (navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1);
      var isStandalone = window.matchMedia("(display-mode: standalone)").matches
        || window.navigator.standalone === true;
      var hint = document.getElementById("ios-install-hint");
      if (hint && isIOS && !isStandalone) hint.classList.add("show");
    })();
    </script>
    """

    page("keyverse", body, base: "", manifest_scope: "")
  end

  def render_offline do
    body = """
    <div class="login offline-page">
      <h1>You’re offline</h1>
      <p>keyverse can’t reach the network. Cached pages may still open.</p>
      <p><a href="/">Try again</a></p>
    </div>
    """

    page("Offline · keyverse", body, base: "", manifest_scope: "")
  end

  @doc """
  Client-side read-only local pack mount shell (ADR 0017 Phase 1).
  No server-side pack; File System Access / OPFS via pack-store.js.
  """
  def render_local_mount do
    body = """
    <div class="local-shell">
      <div class="local-topbar ui">
        <span class="local-badge" id="local-badge" hidden></span>
        <p id="local-status" class="local-status muted" role="status" hidden></p>
      </div>
      <div id="local-app" data-testid="local-app"></div>
    </div>
    <script src="/pack-store.js"></script>
    <script src="/local-mount.js"></script>
    """

    page("keyverse", body, base: "", manifest_scope: "")
  end

  def render_dead_link do
    body = """
    <div class="login">
      <h1>keyverse</h1>
      <p class="lead">That link didn’t open anything.</p>
      <p class="muted"><a href="/">Try your key again</a>
        · <a href="/setup">Create a new key</a></p>
    </div>
    """

    page("keyverse", body, base: "", manifest_scope: "")
  end

  def door_share_chip(door) when is_binary(door) and door != "" do
    """
    <div class="door-share-wrap" id="door-share-wrap" data-open="0">
      <button type="button" class="door-share" id="door-share" data-key="#{esc(door)}"
        title="Share your notes link" aria-label="Share notes link: #{esc(door)}"
        aria-expanded="false" aria-controls="door-share-panel">
        <span class="door-share-key">#{esc(door)}</span>
        <span class="door-share-hint" aria-hidden="true">↗</span>
      </button>
      <div class="door-share-panel" id="door-share-panel" role="dialog"
        aria-label="Share your notes" hidden>
        <div class="door-share-head">
          <div class="door-share-title" id="door-share-title">#{esc(door)}</div>
          <button type="button" class="door-share-x" id="door-share-close"
            title="Close" aria-label="Close share">×</button>
        </div>
        <div class="door-share-qr" id="door-share-qr" aria-busy="true"></div>
        <div class="door-share-actions">
          <button type="button" class="door-share-action" id="door-share-action">Share</button>
          <button type="button" class="door-share-copy" id="door-share-copy">Copy link</button>
        </div>
      </div>
    </div>
    <script src="/door-share.js"></script>
    """
  end

  def door_share_chip(_), do: ""

  def ref_search_html(base) do
    # Match original door markup: single search field + suggest list (Enter to go; no Go button).
    """
    <div class="ref-search" id="ref-search">
      <form action="#{esc(base)}/go" method="get" id="ref-form" role="search" autocomplete="off">
        <input class="ui" type="text" name="q" id="ref-input"
          placeholder="John 3:16" autofocus autocomplete="off" autocorrect="off"
          autocapitalize="off" spellcheck="false" inputmode="search"
          role="combobox" aria-autocomplete="list" aria-expanded="false"
          aria-controls="ref-suggest" aria-haspopup="listbox">
      </form>
      <ul class="ref-suggest" id="ref-suggest" role="listbox" hidden></ul>
    </div>
    <script src="/ref-search.js"></script>
    """
  end

  def crypto_bar(locked?) do
    """
    <div class="crypto-bar ui" id="crypto-bar" data-locked="#{if locked?, do: "1", else: "0"}">
      <span class="crypto-status" id="crypto-status"></span>
      <button type="button" class="crypto-btn" id="crypto-unlock" hidden>Unlock</button>
      <button type="button" class="crypto-btn" id="crypto-set" hidden>Set passphrase</button>
      <button type="button" class="crypto-btn" id="crypto-clear" hidden>Lock</button>
    </div>
    <script src="/crypto-bar.js"></script>
    """
  end

  def render_index(pack_dir, door, base) do
    notes = Note.list(pack_dir)
    tree = home_tree_html(notes, base)
    man = Keyverse.PackTransfer.manifest(pack_dir)

    body = """
    <header class="ui home-head">
      <h1>keyverse</h1>
      #{door_share_chip(door)}
    </header>
    #{crypto_bar(false)}
    #{ref_search_html(base)}
    <section class="home-notes">
      <h2 class="ui muted">Notes</h2>
      #{tree}
    </section>
    #{pack_ownership_html(base, man)}
    #{site_footer(true)}
    <script src="/home-tree.js"></script>
    """

    page("keyverse", body, base: base)
  end

  defp pack_ownership_html(base, man) do
    notes = man.notes || 0
    atts = man.attachments || 0

    note_bit = "#{notes} note#{if notes == 1, do: "", else: "s"}"
    file_bit = "#{atts} file#{if atts == 1, do: "", else: "s"}"

    """
    <section class="pack-own ui" id="pack-own" aria-label="Backup">
      <div class="pack-own-row">
        <span class="muted pack-own-sum">#{note_bit} · #{file_bit}</span>
        <span class="pack-own-dot muted" aria-hidden="true">·</span>
        <a class="pack-own-link" href="#{esc(base)}/api/pack/export" download>Export</a>
        <span class="pack-own-dot muted" aria-hidden="true">·</span>
        <form class="pack-own-import" id="pack-import-form" action="#{esc(base)}/api/pack/import?mode=merge" method="post" enctype="multipart/form-data">
          <label class="pack-own-link pack-own-file">
            Import
            <input type="file" name="pack" accept=".zip,application/zip" required hidden>
          </label>
          <label class="pack-own-replace muted" title="Clear existing notes before import">
            <input type="checkbox" id="pack-import-replace"> Replace
          </label>
        </form>
      </div>
      <p id="pack-import-status" class="muted pack-own-status" role="status" hidden></p>
    </section>
    <script>
    (function () {
      var form = document.getElementById("pack-import-form");
      var status = document.getElementById("pack-import-status");
      var replace = document.getElementById("pack-import-replace");
      if (!form) return;
      var file = form.querySelector('input[type=file]');
      file.addEventListener("change", function () {
        if (!file.files || !file.files[0]) return;
        var mode = replace && replace.checked ? "replace" : "merge";
        var fd = new FormData();
        fd.append("pack", file.files[0]);
        status.hidden = false;
        status.textContent = "Importing…";
        fetch(BASE + "/api/pack/import?mode=" + mode, { method: "POST", body: fd, credentials: "same-origin" })
          .then(function (r) { return r.json().then(function (j) { return { ok: r.ok, j: j }; }); })
          .then(function (x) {
            if (x.ok) {
              status.textContent = "Imported. Reloading…";
              location.reload();
            } else {
              status.textContent = (x.j && x.j.error) ? x.j.error : "Import failed";
            }
          })
          .catch(function (e) { status.textContent = "Import failed"; });
        file.value = "";
      });
    })();
    </script>
    """
  end

  defp home_tree_html(notes, base) do
    tree = Tree.build_home_note_tree(notes)

    if tree == [] do
      ~s(<p class="muted">No notes yet. Search a passage above to start.</p>)
    else
      body = Enum.map_join(tree, "\n", &render_home_tree_node(&1, 0, base))
      ~s(<div class="note-tree" id="note-tree">#{body}</div>)
    end
  end

  @nt_icon_edit ~s(<svg width="14" height="14" viewBox="0 0 256 256" fill="none" aria-hidden="true"><polygon points="128 160 96 160 96 128 192 32 224 64 128 160" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="16"/><line x1="168" y1="56" x2="200" y2="88" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="16"/><path d="M216,128v80a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V48a8,8,0,0,1,8-8h80" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="16"/></svg>)
  @nt_icon_read ~s(<svg width="14" height="14" viewBox="0 0 256 256" fill="none" aria-hidden="true"><path d="M128,88a32,32,0,0,1,32-32h72V200H160a32,32,0,0,0-32,32" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="16"/><path d="M24,200H96a32,32,0,0,1,32,32V88A32,32,0,0,0,96,56H24Z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="16"/></svg>)

  defp render_home_tree_node(node, depth, base) do
    kids = Map.get(node, :children) || []
    has_kids = kids != []

    {id, note_href, read_href, ref, time_iso, sub, is_chapter} =
      case node do
        %{kind: :folder} = n ->
          c = n[:count] || Tree.count_tree_notes(n)
          sub = "#{c} note" <> if(c == 1, do: "", else: "s")

          {
            "folder:#{n.slug}",
            "#{base}/note/#{n.slug}",
            "#{base}/read/#{n.slug}",
            n.label,
            n.updated_at,
            sub,
            true
          }

        %{kind: :note, entry: entry} ->
          scope = entry.scope
          note = entry.note

          {
            "note:#{scope.slug}",
            "#{base}/note/#{scope.slug}",
            "#{base}/read/#{scope.slug}",
            Scope.display(scope),
            note["updated_at"],
            Tree.excerpt(note),
            scope.kind == "chapter"
          }
      end

    chev =
      if has_kids do
        ~s(<button type="button" class="nt-chev" aria-label="Collapse" aria-expanded="true"></button>)
      else
        ~s(<span class="nt-chev is-leaf" aria-hidden="true"></span>)
      end

    row_cls =
      [
        "note-row",
        if(match?(%{kind: :folder}, node), do: "is-folder", else: nil),
        if(is_chapter, do: "is-chapter", else: nil),
        if(has_kids, do: "has-kids", else: nil)
      ]
      |> Enum.reject(&is_nil/1)
      |> Enum.join(" ")

    meta = """
    <span class="nt-meta">
      <a class="nt-act nt-open" href="#{esc(note_href)}" title="Open note" aria-label="Open note">#{@nt_icon_edit}</a>
      <a class="nt-act nt-read" href="#{esc(read_href)}" title="Read" aria-label="Read">#{@nt_icon_read}</a>
      #{if time_iso && time_iso != "", do: ~s(<span class="muted nt-time">#{esc(Tree.rel_time(time_iso))}</span>), else: ""}
    </span>
    """

    main_inner = """
      <span class="nt-top">
        <span class="ref">#{esc(ref)}</span>
        #{meta}
      </span>
      <div class="muted nt-ex">#{esc(sub)}</div>
    """

    main =
      if has_kids do
        ~s(<div class="nt-main nt-fold" role="button" tabindex="0" aria-expanded="true">#{main_inner}</div>)
      else
        ~s(<div class="nt-main nt-open-read" role="link" tabindex="0" data-href="#{esc(read_href)}">#{main_inner}</div>)
      end

    kids_html =
      if has_kids do
        inner = Enum.map_join(kids, "", &render_home_tree_node(&1, depth + 1, base))
        ~s(<div class="nt-kids">#{inner}</div>)
      else
        ""
      end

    """
    <div class="nt-node" data-id="#{esc(id)}" data-depth="#{depth}">
      <div class="#{row_cls}" style="--depth:#{depth}">
        #{chev}
        #{main}
      </div>
      #{kids_html}
    </div>
    """
  end

  defp excerpt_note(note), do: Tree.excerpt(note)

  def render_editor(pack_dir, scope, base) do
    note = Note.read(pack_dir, scope.slug)
    locked? = note != nil and Note.encrypted?(note)
    display = Scope.display(scope)

    initial =
      cond do
        locked? -> [%{"id" => "b_new", "indent" => 0, "text" => ""}]
        note && note["blocks"] != [] -> note["blocks"]
        true -> [%{"id" => "b_new", "indent" => 0, "text" => ""}]
      end

    atts = if locked?, do: [], else: (note && note["attachments"]) || []
    cipher_json = if locked?, do: Jason.encode!(note["cipher"]), else: "null"
    rel = related_html(pack_dir, scope, base)
    passage = passage_strip_html(scope)

    body = """
    <header class="ui editor-head">
      <a href="#{esc(base)}/" class="muted editor-back" aria-label="Home">&larr;</a>
      <h1>#{esc(display)}</h1>
      <div class="editor-head-actions">
        <a class="muted" href="#{esc(base)}/read/#{esc(scope.slug)}">read</a>
        <span id="status"></span>
      </div>
    </header>
    #{crypto_bar(locked?)}
    <div id="note-main" #{if locked?, do: "hidden", else: ""}>
    #{passage}
    <div id="editor"></div>
    <div id="att-root"></div>
    </div>
    <div id="crypto-gate" class="crypto-lock" #{if locked?, do: "", else: "hidden"}>
      <h2>Encrypted note</h2>
      <p>This note is sealed with a client-side passphrase (cowyo-style). The server only stores ciphertext. Enter the passphrase or open with <code>#pw=…</code> in the URL.</p>
      <form id="crypto-unlock-form">
        <input type="password" id="crypto-pw" placeholder="Passphrase" autocomplete="current-password" required>
        <button type="submit">Unlock</button>
      </form>
      <p class="muted" id="crypto-err" hidden>Could not decrypt — wrong passphrase?</p>
    </div>
    #{rel}
    <script type="application/json" id="page-meta">#{Jason.encode!(%{
      slug: scope.slug,
      display: display,
      kind: scope.kind,
      max_attach_bytes: Config.max_attach_bytes(),
      max_attach_per_note: Config.max_attach_per_note()
    })}</script>
    <script type="application/json" id="initial-blocks">#{Jason.encode!(initial)}</script>
    <script type="application/json" id="initial-atts">#{Jason.encode!(atts)}</script>
    <script type="application/json" id="initial-cipher">#{cipher_json}</script>
    <script src="/outliner.js"></script>
    <script src="/editor-page.js"></script>
    """

    page(display, body, base: base)
  end

  @doc false
  def passage_strip_html(%Scope{kind: kind, parsed: p} = scope)
      when kind in ["verse", "range"] and is_map(p) do
    book = p.book
    chapter = p.chapter
    v0 = p.verse
    v1 = p.verse_end || v0

    if is_binary(book) and is_integer(chapter) and is_integer(v0) do
      case Keyverse.TextCache.get_chapter(book, chapter) do
        {:ok, doc} ->
          rows =
            (doc["verses"] || [])
            |> Enum.filter(fn row ->
              v = row_verse_num(row)
              is_integer(v) and v >= v0 and v <= v1
            end)

          if rows == [] do
            ""
          else
            body =
              Enum.map_join(rows, "\n", fn row ->
                v = row_verse_num(row)
                t = to_string(row["text"] || row["t"] || "")

                ~s(<p class="passage-v" data-v="#{v}"><sup class="passage-vn">#{v}</sup>) <>
                  esc(t) <> "</p>"
              end)

            """
            <section class="passage-strip" aria-label="#{esc(Scope.display(scope))} · BSB" data-tr="BSB">
              <div class="passage-strip-body">#{body}</div>
            </section>
            """
          end

        _ ->
          ""
      end
    else
      ""
    end
  end

  def passage_strip_html(_), do: ""

  defp row_verse_num(row) when is_map(row) do
    case row["v"] || row["verse"] do
      n when is_integer(n) -> n
      n when is_binary(n) ->
        case Integer.parse(n) do
          {i, _} -> i
          :error -> nil
        end
      _ -> nil
    end
  end

  defp related_html(pack_dir, scope, base) do
    notes = Note.list(pack_dir)
    a_int = Tree.scope_interval(scope)

    buckets =
      Enum.reduce(notes, %{contains: [], within: [], overlaps: []}, fn n, acc ->
        slug = get_in(n, ["scope", "slug"])

        if slug == scope.slug do
          acc
        else
          case Scope.parse(get_in(n, ["scope", "osis"]) || slug) do
            nil ->
              acc

            other ->
              case Tree.relate_intervals(a_int, Tree.scope_interval(other)) do
                :contains -> update_in(acc.contains, &[{other, n} | &1])
                :within -> update_in(acc.within, &[{other, n} | &1])
                :overlaps -> update_in(acc.overlaps, &[{other, n} | &1])
                _ -> acc
              end
          end
        end
      end)

    [
      related_section("contains", "Within", "Notes on passages inside #{Scope.display(scope)}", Enum.reverse(buckets.contains), base),
      related_section("within", "Part of", "Broader passages this note sits in", Enum.reverse(buckets.within), base),
      related_section("overlaps", "Overlaps", "Ranges that partially overlap this note", Enum.reverse(buckets.overlaps), base)
    ]
    |> Enum.reject(&(&1 == ""))
    |> Enum.join("\n")
  end

  defp related_section(_kind, _label, _sub, [], _base), do: ""

  defp related_section(_kind, label, sub, entries, base) do
    items =
      Enum.map(entries, fn {sc, n} ->
        href = "#{base}/note/#{sc.slug}"
        ex = excerpt_note(n)

        """
        <li class="note-row"><a href="#{esc(href)}">
          <span class="note-ref">#{esc(Scope.display(sc))}</span>
          <span class="note-ex">#{esc(ex)}</span>
        </a></li>
        """
      end)

    """
    <section class="related ui">
      <h2>#{esc(label)}</h2>
      <p class="muted">#{esc(sub)}</p>
      <ul class="note-list">#{Enum.join(items, "")}</ul>
    </section>
    """
  end

  @doc """
  Build reader payload for SSR and `GET /api/read/:slug`.
  Returns `{:ok, map}` or `{:error, reason}`.
  """
  def build_read_bundle(pack_dir, scope, base) do
    book = scope.parsed.book
    chapter = scope.parsed.chapter
    chapter_scope = Scope.parse("#{book}.#{chapter}")
    display = if chapter_scope, do: Scope.display(chapter_scope), else: Scope.display(scope)

    text_task = Task.async(fn -> Keyverse.TextCache.get_chapter(book, chapter) end)
    notes_task = Task.async(fn -> Note.list_for_chapter(pack_dir, book, chapter) end)
    text_result = Task.await(text_task, 15_000)
    notes = Task.await(notes_task, 15_000)

    case text_result do
      {:error, reason} ->
        {:error, reason}

      {:ok, text} ->
        hl =
          if scope.kind == "chapter" do
            nil
          else
            Tree.scope_interval(scope)
          end

        verse_notes = %{}
        range_notes = %{}
        range_cover = MapSet.new()
        chapter_note = nil

        {verse_notes, range_notes, range_cover, chapter_note} =
          Enum.reduce(notes, {verse_notes, range_notes, range_cover, chapter_note}, fn note, acc ->
            {vn, rn, rc, cn} = acc
            other = Scope.parse(get_in(note, ["scope", "osis"]) || get_in(note, ["scope", "slug"]))

            cond do
              is_nil(other) ->
                acc

              other.parsed.book != book ->
                acc

              other.parsed.chapter != chapter ->
                acc

              other.kind == "chapter" ->
                {vn, rn, rc, note}

              other.kind == "verse" ->
                {Map.put(vn, other.parsed.verse, note), rn, rc, cn}

              true ->
                start_v = other.parsed.verse
                end_v = other.parsed.verse_end || start_v
                list = Map.get(rn, end_v, []) ++ [%{note: note, scope: other}]
                rn = Map.put(rn, end_v, list)
                rc = Enum.reduce(start_v..end_v, rc, &MapSet.put(&2, &1))
                {vn, rn, rc, cn}
            end
          end)

        seed = %{}

        seed =
          if chapter_note && not Note.encrypted?(chapter_note) && chapter_note["blocks"] do
            Map.put(seed, chapter_scope.slug, chapter_note["blocks"])
          else
            seed
          end

        {rows, seed} =
          Enum.reduce(text["verses"] || [], {"", seed}, fn vrow, {html, seed} ->
            v = vrow["v"]
            t = vrow["text"] || ""
            note = Map.get(verse_notes, v)
            ranges = Map.get(range_notes, v, [])
            in_hl = hl && Tree.pos(chapter, v) >= hl.s && Tree.pos(chapter, v) <= hl.e
            slug = "#{String.downcase(to_string(book))}.#{chapter}.#{v}"

            seed =
              if note && not Note.encrypted?(note) && note["blocks"] do
                Map.put(seed, slug, note["blocks"])
              else
                seed
              end

            seed =
              Enum.reduce(ranges, seed, fn e, s ->
                if not Note.encrypted?(e.note),
                  do: Map.put(s, e.scope.slug, e.note["blocks"] || []),
                  else: s
              end)

            v_scope = Scope.parse(slug)

            has_verse =
              note &&
                (Note.encrypted?(note) ||
                   Enum.any?(note["blocks"] || [], fn b -> String.trim(to_string(b["text"] || "")) != "" end))

            has_notes = has_verse || ranges != [] || MapSet.member?(range_cover, v)

            range_html =
              Enum.map_join(ranges, "\n", fn e ->
                reader_note_html(e.scope, e.note, base, true)
              end)

            verse_html =
              if has_verse, do: reader_note_html(v_scope, note, base, true), else: ""

            notes_inner = ""

            notes_inner =
              if range_html != "" do
                notes_inner <>
                  ~s(<div class="note-group passage">) <>
                  if(verse_html == "", do: "", else: ~s(<div class="note-group-title">Passage</div>)) <>
                  range_html <> ~s(</div>)
              else
                notes_inner
              end

            notes_inner =
              if verse_html != "" do
                notes_inner <>
                  ~s(<div class="note-group verse-local">) <>
                  if(ranges != [], do: ~s(<div class="note-group-title">This verse</div>), else: "") <>
                  verse_html <> ~s(</div>)
              else
                notes_inner
              end

            v_cls =
              ["verse", if(in_hl, do: "hl", else: nil), if(has_notes, do: "has-notes", else: nil), if(has_verse, do: "has-verse-note", else: nil)]
              |> Enum.reject(&is_nil/1)
              |> Enum.join(" ")

            row = """
            <div class="#{v_cls}" data-slug="#{esc(slug)}" data-v="#{v}" id="v#{v}">
              <p class="vtext"><sup>#{v}</sup>#{esc(t)}<span class="vstatus"></span></p>
              <div class="vnotes">#{notes_inner}</div>
            </div>
            """

            {html <> row, seed}
          end)

        chapter_note_html =
          if chapter_note do
            ~s(<div class="chapter-note" id="chapter-note">#{reader_note_html(chapter_scope, chapter_note, base, false)}</div>)
          else
            ~s(<div class="chapter-note" id="chapter-note" hidden></div>)
          end

        prev = Scope.neighbor_chapter(chapter_scope || scope, -1)
        next = Scope.neighbor_chapter(chapter_scope || scope, 1)

        meta = %{
          slug: (chapter_scope || scope).slug,
          display: display,
          book: book,
          chapter: chapter,
          kind: scope.kind,
          hl_slug: scope.slug,
          prev_slug: if(prev, do: prev.slug, else: nil),
          next_slug: if(next, do: next.slug, else: nil),
          chapter_note_slug: if(chapter_scope, do: chapter_scope.slug, else: nil)
        }

        {:ok,
         %{
           meta: meta,
           seed: seed,
           text: %{
             "translation" => text["translation"] || "BSB",
             "book" => book,
             "chapter" => chapter,
             "verses" => text["verses"] || []
           },
           html: %{
             chapter_note: chapter_note_html,
             verses: rows
           }
         }}
    end
  end

  def render_read(pack_dir, scope, base) do
    case build_read_bundle(pack_dir, scope, base) do
      {:error, reason} ->
        body = """
        <p>Could not load text (#{esc(to_string(reason))}).
          <a href="#{esc(base)}/note/#{esc(scope.slug)}">Open note editor</a>.</p>
        """

        page("keyverse", body, base: base)

      {:ok, bundle} ->
        meta = bundle.meta
        display = meta.display

        prev_btn =
          if meta.prev_slug do
            ~s(<button type="button" class="reader-dock-item reader-nav" id="reader-prev" data-slug="#{esc(meta.prev_slug)}" aria-label="Previous chapter"><span class="reader-dock-ico" aria-hidden="true"><i class="ph ph-caret-left"></i></span><span class="reader-dock-lbl">Prev</span></button>)
          else
            ~s(<span class="reader-dock-item is-disabled" aria-hidden="true"><span class="reader-dock-ico"><i class="ph ph-caret-left"></i></span><span class="reader-dock-lbl">Prev</span></span>)
          end

        next_btn =
          if meta.next_slug do
            ~s(<button type="button" class="reader-dock-item reader-nav" id="reader-next" data-slug="#{esc(meta.next_slug)}" aria-label="Next chapter"><span class="reader-dock-ico" aria-hidden="true"><i class="ph ph-caret-right"></i></span><span class="reader-dock-lbl">Next</span></button>)
          else
            ~s(<span class="reader-dock-item is-disabled" aria-hidden="true"><span class="reader-dock-ico"><i class="ph ph-caret-right"></i></span><span class="reader-dock-lbl">Next</span></span>)
          end

        body = """
        <header class="ui reader-head">
          <a href="#{esc(base)}/" class="muted reader-back" aria-label="Home">&larr;</a>
          <h1 id="reader-title">#{esc(display)}</h1>
        </header>
        <nav class="reader-dock" id="reader-dock" aria-label="Chapter tools">
          #{prev_btn}
          <button type="button" class="reader-dock-item" id="expand-notes"
            aria-pressed="false" aria-label="Expand all verse notes"
            data-label-expand="Notes" data-label-collapse="Fold">
            <span class="reader-dock-ico" aria-hidden="true"><i class="ph ph-list-dashes"></i></span>
            <span class="reader-dock-lbl" data-expand-lbl>Notes</span>
          </button>
          <a class="reader-dock-item" id="chapter-note-link"
            href="#{esc(base)}/note/#{esc(meta.chapter_note_slug || scope.slug)}"
            aria-label="Chapter note">
            <span class="reader-dock-ico" aria-hidden="true"><i class="ph ph-book-open-text"></i></span>
            <span class="reader-dock-lbl">Chapter</span>
          </a>
          #{next_btn}
        </nav>
        <div id="reader-root" data-slug="#{esc(meta.slug)}">
          #{bundle.html.chapter_note}
          <div id="reader-verses">#{bundle.html.verses}</div>
        </div>
        <script type="application/json" id="page-meta">#{Jason.encode!(meta)}</script>
        <script type="application/json" id="verse-seeds">#{Jason.encode!(bundle.seed)}</script>
        <script src="/outliner.js"></script>
        <script src="/reader-page.js"></script>
        """

        page(display, body, base: base)
    end
  end

  defp reader_note_html(nil, _note, _base, _label), do: ""

  defp reader_note_html(scope, note, base, label) do
    display = Scope.display(scope)
    lo = scope.parsed.verse || ""
    hi = scope.parsed.verse_end || lo

    range_attrs =
      if scope.kind == "range" do
        ~s( data-lo="#{esc(to_string(lo))}" data-hi="#{esc(to_string(hi))}")
      else
        ""
      end

    if Note.encrypted?(note) do
      show_label = label && scope.kind != "verse"

      """
      <div class="note encrypted" data-kind="#{esc(scope.kind)}" data-slug="#{esc(scope.slug)}"#{range_attrs} data-encrypted="1">
        #{if show_label, do: ~s(<div class="note-label">#{esc(display)}</div>), else: ""}
        <div class="note-body"><p class="muted ui" style="margin:.35rem 0">Encrypted — <a href="#{esc(base)}/note/#{esc(scope.slug)}">open to unlock</a></p></div>
        <div class="note-edit" hidden></div>
      </div>
      """
    else
      blocks = note["blocks"] || []
      has = Enum.any?(blocks, fn b -> String.trim(to_string(b["text"] || "")) != "" end) or blocks != []
      if not has and scope.kind != "verse" do
        ""
      else
        show_label = label && scope.kind != "verse"
        body = if blocks == [], do: "", else: render_outline(blocks)

        """
        <div class="note" data-kind="#{esc(scope.kind)}" data-slug="#{esc(scope.slug)}"#{range_attrs}>
          #{if show_label, do: ~s(<div class="note-label">#{esc(display)}</div>), else: ""}
          <div class="note-body">#{body}</div>
          <div class="note-edit" hidden></div>
        </div>
        """
      end
    end
  end

  defp render_outline(blocks) do
    items = List.wrap(blocks)
    if items == [], do: "", else: do_render_outline(items)
  end

  defp do_render_outline(items) do
    hidden = collapse_hidden(items)

    inner =
      items
      |> Enum.with_index()
      |> Enum.map(fn {b, i} ->
        if MapSet.member?(hidden, i) do
          ""
        else
          depth = max(0, trunc(b["indent"] || 0))
          empty = String.trim(to_string(b["text"] || "")) == ""
          has_kids = i + 1 < length(items) and max(0, trunc(Enum.at(items, i + 1)["indent"] || 0)) > depth
          collapsed = b["collapsed"] && has_kids

          cls =
            ["oline", if(empty, do: "blank"), if(has_kids, do: "has-kids"), if(collapsed, do: "collapsed")]
            |> Enum.reject(&is_nil/1)
            |> Enum.join(" ")

          id = esc(to_string(b["id"] || ""))
          aria = if collapsed, do: "Expand", else: "Collapse"
          text = if empty, do: "", else: esc(to_string(b["text"] || ""))

          """
          <div class="#{cls}" style="--depth:#{depth}" data-id="#{id}" title="#{id}">
            <span class="ochev" role="button" tabindex="-1" aria-label="#{aria}"></span>
            <span class="odot" aria-hidden="true"></span>
            <span class="otxt">#{text}</span>
          </div>
          """
        end
      end)
      |> Enum.join("")

    ~s(<div class="outline">#{inner}</div>)
  end

  defp collapse_hidden(items) do
    items
    |> Enum.with_index()
    |> Enum.reduce(MapSet.new(), fn {b, i}, hid ->
      if b["collapsed"] do
        base = max(0, trunc(b["indent"] || 0))

        Enum.reduce_while((i + 1)..max(i, length(items) - 1)//1, hid, fn j, h ->
          if j >= length(items) do
            {:halt, h}
          else
            d = max(0, trunc(Enum.at(items, j)["indent"] || 0))
            if d <= base, do: {:halt, h}, else: {:cont, MapSet.put(h, j)}
          end
        end)
      else
        hid
      end
    end)
  end

  def web_manifest(start_url) do
    %{
      name: "keyverse",
      short_name: "keyverse",
      description: "Scripture notes — multiword key, no account",
      start_url: start_url,
      scope: "/",
      display: "standalone",
      background_color: "#f7f4ef",
      theme_color: "#1c1915",
      icons: [
        %{src: "/icons/icon-192.png", sizes: "192x192", type: "image/png"},
        %{src: "/icons/icon-512.png", sizes: "512x512", type: "image/png"},
        %{
          src: "/icons/icon-maskable-192.png",
          sizes: "192x192",
          type: "image/png",
          purpose: "maskable"
        },
        %{
          src: "/icons/icon-maskable-512.png",
          sizes: "512x512",
          type: "image/png",
          purpose: "maskable"
        }
      ]
    }
  end
end
